server {
    listen 80;
    # listen 443 ssl; for ssl you need to use certificates
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # Раздача статичных файлов
    location / {
        try_files $uri /index.html;
    }

    # Логирование (для отладки)
    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;
}
